name: Test quimb

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        testset: [matrix, tensor]
        env: [base]
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, '3.10']

        include:
        - os: macos-latest
          testset: matrix
          env: base
          python-version: 3.9

        - os: macos-latest
          testset: tensor
          env: base
          python-version: 3.9

        - os: windows-latest
          testset: matrix
          env: base
          python-version: 3.9

        - os: windows-latest
          testset: tensor
          env: base
          python-version: 3.9

        - env: torch
          testset: tensor
          os: ubuntu-latest
          python-version: 3.9

        - env: jax
          testset: tensor
          os: ubuntu-latest
          python-version: 3.9

        - env: tensorflow
          testset: tensor
          os: ubuntu-latest
          python-version: 3.9

        - env: slepc
          testset: matrix
          os: ubuntu-latest
          python-version: 3.9

    steps:
    - uses: actions/checkout@v3

    - name: Install micromamba
      uses: mamba-org/provision-with-micromamba@v15
      with:
        environment-file: ci/requirements/py-${{ matrix.env }}.yml
        environment-name: test-env
        extra-specs: python=${{ matrix.python-version }}
        cache-env: true

    - name: Matrix submodule tests with pytest
      if: ${{ matrix.testset == 'matrix' }}
      run: pytest tests/ --cov=quimb --cov-report=xml --ignore=tests/test_tensor

    - name: Tensor tests with pytest
      if: ${{ matrix.testset == 'tensor' }}
      run: pytest tests/test_tensor --cov=quimb --cov-report=xml

    - name: Report to codecov
      uses: codecov/codecov-action@v3
